<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="richasdys-MacBook-Pro.local"
	name="com.richasdy.HelloTesting.TestNG.TestTimeout" tests="2" failures="1"
	timestamp="12 Oct 2016 08:31:56 GMT" time="5.030" errors="0">
	<testcase name="testThisShouldFail" time="1.022"
		classname="com.richasdy.HelloTesting.TestNG.TestTimeout">
		<failure type="org.testng.internal.thread.ThreadTimeoutException"
			message="Method org.testng.internal.TestNGMethod.testThisShouldFail() didn&#039;t finish within the time-out 1000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method org.testng.internal.TestNGMethod.testThisShouldFail() didn't finish within the time-out 1000
	at com.richasdy.HelloTesting.TestNG.TestTimeout.testThisShouldFail(TestTimeout.java:14)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:46)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:37)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
		</failure>
	</testcase> <!-- testThisShouldFail -->
	<testcase name="testThisShouldPass" time="4.008"
		classname="com.richasdy.HelloTesting.TestNG.TestTimeout" />
</testsuite> <!-- com.richasdy.HelloTesting.TestNG.TestTimeout -->
